[package]
name = "k256-verify"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = {  version = "=2.3.1", default-features = false, features = ["std", "unstable"] }
hex-literal = "0.4"
k256 = { version = "=0.13.4", features = ["arithmetic", "serde", "expose-field", "std", "ecdsa"], default-features = false }

json = "0.12"
json-core = { path = "../../core" }

sha2 = "0.10"
anyhow = "1.0"
hex = "0.4"
rand_core = "0.6.4"

[patch.crates-io]
# Placing these patch statement in the workspace Cargo.toml will add RISC Zero SHA-256 and bigint
# multiplication accelerator support for all downstream usages of the following crates.
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.3-risczero.1" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }

[profile.release]
# Empirically observed to result in the best performance for this binary (in particular, better than
# "fat"). It's often a good idea to experiment with different optimization levels and options.
codegen-units = 1
lto = "thin"
